name: CI

on:
  workflow_dispatch: 
jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate sha
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Build docker image
      run: docker build -t gabriel0611/nlw.service.passin:${{ steps.generate_sha.outputs.sha }} .

    - name: Log into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image
      run: |
        docker push gabriel0611/nlw.service.passin:${{ steps.generate_sha.outputs.sha }}
        docker tag gabriel0611/nlw.service.passin:${{ steps.generate_sha.outputs.sha }} gabriel0611/nlw.service.passin:latest
        docker push gabriel0611/nlw.service.passin:latest

